### ISSUE TITLE
After upgrading nodejs version and hass no resonse from hue bridge

### ISSUE THREAD

**Issue by thundergreen** [dale3h/hue-mqtt-bridge#9]
I updated hass to 0.40.0 and now the bridge doesnt work anymore. hue is reachable username still the same but when watching mosquitto or if i start the bridge manually .. no hue dimmer clicks are recognised :(

**Comment by thundergreen** [comment]
```
TypeError: Cannot read property 'end' of undefined
    at process.exitHandler (/home/pi/node/hue-mqtt-bridge/index.js:111:9)
    at emitOne (events.js:96:13)
    at process.emit (events.js:191:7)
    at process.exit (internal/process.js:162:15)
    at process.uncaughtListener (/usr/lib/node_modules/pm2/node_modules/pmx/lib/notify.js:65:19)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at process.emit (events.js:191:7)
    at process._fatalException (bootstrap_node.js:299:26)
    at process._asyncFatalException [as _fatalException] (/usr/lib/node_modules/pm2/node_modules/async-listener/glue.js:211:34)
TypeError: "listener" argument must be a function
    at Socket.once (events.js:307:11)
    at Socket.connect (net.js:943:10)
    at Socket.connect (/usr/lib/node_modules/pm2/node_modules/async-listener/index.js:76:27)
    at Object.exports.connect.exports.createConnection (net.js:76:35)
    at Object.buildBuilder (/home/pi/node/hue-mqtt-bridge/node_modules/mqtt/lib/connect/tcp.js:16:14)
    at MqttClient.wrapper [as streamBuilder] (/home/pi/node/hue-mqtt-bridge/node_modules/mqtt/lib/connect/index.js:129:36)
    at MqttClient._setupStream (/home/pi/node/hue-mqtt-bridge/node_modules/mqtt/lib/client.js:228:22)
    at new MqttClient (/home/pi/node/hue-mqtt-bridge/node_modules/mqtt/lib/client.js:209:8)
    at Object.connect (/home/pi/node/hue-mqtt-bridge/node_modules/mqtt/lib/connect/index.js:132:10)
    at Object.<anonymous> (/home/pi/node/hue-mqtt-bridge/index.js:119:19)
/home/pi/node/hue-mqtt-bridge/index.js:111
  client.end();
```

**Comment by dannuttall** [comment]
Hey thundergreen,
I just had a lot of problems getting this working on my new RP3 setup. Figured it out eventually and it's running latest version of HASS / Node. I'd recommend re-installing node to see if that helps. These instructions worked for me:
https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=130217

good luck
